/**
 * Intervengine Application API V1Lib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { ApiError } from '../core';
import { Body } from '../models/body';

/**
 * Creates an instance of Content
 */
interface Content {
  id?: string;
  uuid?: string;
  contentTypeId?: string;
  contentType?: string;
  title?: string;
  description?: string;
  contentTags?: unknown[];
  body?: Body[];
  uiConfigs?: string;
  version?: number;
  approvedAt?: string;
  approvedBy?: string;
  rejectedAt?: string;
  rejectedBy?: string;
  publishedAt?: string;
  publishedBy?: string;
  isActive?: boolean;
}

export class ContentError extends ApiError<Content> {}
