/**
 * Intervengine Application API V1Lib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { ApiError } from '@apimatic/core';
import { ApiResponse, RequestOptions } from '../core';
import {
  ApiV1ExtrasSearchRequest,
  apiV1ExtrasSearchRequestSchema,
} from '../models/apiV1ExtrasSearchRequest';
import {
  GroupSearchResult,
  groupSearchResultSchema,
} from '../models/groupSearchResult';
import { Survey, surveySchema } from '../models/survey';
import { number, optional, string } from '../schema';
import { BaseController } from './baseController';

export class ExtrasController extends BaseController {
  /**
   * Search Extra (fields)
   *
   * @param xAPIKEY
   * @param page         current page number
   * @param perPage      a number of records per page
   * @param body
   * @return Response from the API call
   */
  async httpLocalhost8080ApiV1ExtrasSearch(
    xAPIKEY?: string,
    page?: number,
    perPage?: number,
    body?: ApiV1ExtrasSearchRequest,
    requestOptions?: RequestOptions
  ): Promise<ApiResponse<GroupSearchResult>> {
    const req = this.createRequest('POST', '/api/v1/extras/search');
    const mapped = req.prepareArgs({
      xAPIKEY: [xAPIKEY, optional(string())],
      page: [page, optional(number())],
      perPage: [perPage, optional(number())],
      body: [body, optional(apiV1ExtrasSearchRequestSchema)],
    });
    req.header('Content-Type', 'application/json');
    req.header('X-API-KEY', mapped.xAPIKEY);
    req.query('page', mapped.page);
    req.query('per_page', mapped.perPage);
    req.json(mapped.body);
    req.throwOn(400, ApiError, 'Bad Request');
    req.throwOn(401, ApiError, 'Unauthorized');
    req.throwOn(403, ApiError, 'Forbidden');
    req.throwOn(404, ApiError, 'Not Found');
    req.throwOn(500, ApiError, 'Internal Server Error');
    return req.callAsJson(groupSearchResultSchema, requestOptions);
  }

  /**
   * http://localhost:8080/api/v1/extras/:id
   *
   * @param id
   * @param xAPIKEY
   * @return Response from the API call
   */
  async httpLocalhost8080ApiV1ExtrasId(
    id: number,
    xAPIKEY?: string,
    requestOptions?: RequestOptions
  ): Promise<ApiResponse<Survey>> {
    const req = this.createRequest('GET');
    const mapped = req.prepareArgs({
      id: [id, number()],
      xAPIKEY: [xAPIKEY, optional(string())],
    });
    req.header('X-API-KEY', mapped.xAPIKEY);
    req.appendTemplatePath`/api/v1/extras/${mapped.id}`;
    return req.callAsJson(surveySchema, requestOptions);
  }
}
