/**
 * Intervengine Application API V1Lib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { array, lazy, number, object, optional, Schema } from '../schema';
import { Result1, result1Schema } from './result1';

/** A search model for activity plan cards */
export interface ActivityPlanCardSearch {
  results?: Result1[];
  total?: number;
}

export const activityPlanCardSearchSchema: Schema<ActivityPlanCardSearch> = object(
  {
    results: ['results', optional(array(lazy(() => result1Schema)))],
    total: ['total', optional(number())],
  }
);
