/**
 * Intervengine Application API V1Lib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { array, lazy, object, optional, Schema, string } from '../schema';
import {
  ActivityMeasureType,
  activityMeasureTypeSchema,
} from './activityMeasureType';

export interface ActivityPlan {
  id?: string;
  activityPlanName?: string;
  activityTypeName?: string;
  activityTypeCode?: string;
  activityTypeGroupCode?: string;
  activityMeasureTypes?: ActivityMeasureType[];
}

export const activityPlanSchema: Schema<ActivityPlan> = object({
  id: ['id', optional(string())],
  activityPlanName: ['activityPlanName', optional(string())],
  activityTypeName: ['activityTypeName', optional(string())],
  activityTypeCode: ['activityTypeCode', optional(string())],
  activityTypeGroupCode: ['ActivityTypeGroupCode', optional(string())],
  activityMeasureTypes: [
    'ActivityMeasureTypes',
    optional(array(lazy(() => activityMeasureTypeSchema))),
  ],
});
