/**
 * Intervengine Application API V1Lib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  boolean,
  lazy,
  nullable,
  object,
  optional,
  Schema,
  string,
  unknown,
} from '../schema';
import { Data, dataSchema } from './data';
import { UiConfigs2, uiConfigs2Schema } from './uiConfigs2';

export interface ActivityPlanCard {
  id?: string;
  activityPlanId: string;
  title: string;
  description?: unknown | null;
  imageUrl?: string;
  isOneOff: boolean;
  scheduledAt?: string;
  reportedAt?: string | null;
  data?: Data;
  /** The name of journey linked to this card if any */
  associatedJourney?: string | null;
  uiConfigs?: UiConfigs2;
}

export const activityPlanCardSchema: Schema<ActivityPlanCard> = object({
  id: ['id', optional(string())],
  activityPlanId: ['activityPlanId', string()],
  title: ['title', string()],
  description: ['description', optional(nullable(unknown()))],
  imageUrl: ['imageUrl', optional(string())],
  isOneOff: ['isOneOff', boolean()],
  scheduledAt: ['scheduledAt', optional(string())],
  reportedAt: ['reportedAt', optional(nullable(string()))],
  data: ['data', optional(lazy(() => dataSchema))],
  associatedJourney: ['associatedJourney', optional(nullable(string()))],
  uiConfigs: ['uiConfigs', optional(lazy(() => uiConfigs2Schema))],
});
