/**
 * Intervengine Application API V1Lib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { array, object, optional, Schema, string } from '../schema';

export interface ActivityMeasureType {
  measureTypeId?: string;
  measureTypeName?: string;
  measureTypeCode?: string;
  measureDataType?: string;
  measureTypeOptions?: string[];
}

export const activityMeasureTypeSchema: Schema<ActivityMeasureType> = object({
  measureTypeId: ['measureTypeId', optional(string())],
  measureTypeName: ['measureTypeName', optional(string())],
  measureTypeCode: ['MeasureTypeCode', optional(string())],
  measureDataType: ['MeasureDataType', optional(string())],
  measureTypeOptions: ['MeasureTypeOptions', optional(array(string()))],
});
