/**
 * Intervengine Application API V1Lib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { nullable, object, optional, Schema, string, unknown } from '../schema';

export interface ActivityValue2 {
  id?: string;
  measureTypeId?: string;
  reportedValue?: unknown | null;
}

export const activityValue2Schema: Schema<ActivityValue2> = object({
  id: ['id', optional(string())],
  measureTypeId: ['measureTypeId', optional(string())],
  reportedValue: ['reportedValue', optional(nullable(unknown()))],
});
