/**
 * Intervengine Application API V1Lib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { array, lazy, object, optional, Schema, string } from '../schema';
import { ActivityPlan, activityPlanSchema } from './activityPlan';
import { Data2, data2Schema } from './data2';

export interface ApiV1ParticipantsActivityPlansDataResponse {
  participantId?: string;
  activityPlan?: ActivityPlan;
  data?: Data2[];
}

export const apiV1ParticipantsActivityPlansDataResponseSchema: Schema<ApiV1ParticipantsActivityPlansDataResponse> = object(
  {
    participantId: ['participantId', optional(string())],
    activityPlan: ['activityPlan', optional(lazy(() => activityPlanSchema))],
    data: ['data', optional(array(lazy(() => data2Schema)))],
  }
);
