/**
 * Intervengine Application API V1Lib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { boolean, object, optional, Schema, string } from '../schema';

export interface ApiV1ParticipantsActivityPlanCardsSearchRequest {
  /** a type of Activity Plan. eg) GENERAL_ACTIVITY, SURVEY, CONTENT etc. */
  activityPlanType?: string;
  /** the name or title of the activity plan card */
  activityPlanName?: string;
  fromDate?: string;
  toDate?: string;
  /** returns only reporetd cards if true */
  isReported?: boolean;
  isActive?: boolean;
}

export const apiV1ParticipantsActivityPlanCardsSearchRequestSchema: Schema<ApiV1ParticipantsActivityPlanCardsSearchRequest> = object(
  {
    activityPlanType: ['activityPlanType', optional(string())],
    activityPlanName: ['activityPlanName', optional(string())],
    fromDate: ['fromDate', optional(string())],
    toDate: ['toDate', optional(string())],
    isReported: ['isReported', optional(boolean())],
    isActive: ['isActive', optional(boolean())],
  }
);
