/**
 * Intervengine Application API V1Lib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { boolean, object, optional, Schema, string } from '../schema';

export interface ApiV1TagsSearchRequest {
  code?: string;
  name?: string;
  isActive?: boolean;
}

export const apiV1TagsSearchRequestSchema: Schema<ApiV1TagsSearchRequest> = object(
  {
    code: ['code', optional(string())],
    name: ['name', optional(string())],
    isActive: ['isActive', optional(boolean())],
  }
);
