/**
 * Intervengine Application API V1Lib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { object, optional, Schema, string } from '../schema';

export interface ApiV1ParticipantsEmailRequest {
  email?: string;
}

export const apiV1ParticipantsEmailRequestSchema: Schema<ApiV1ParticipantsEmailRequest> = object(
  { email: ['email', optional(string())] }
);
