/**
 * Intervengine Application API V1Lib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { array, object, Schema, string } from '../schema';

export interface ApiV1ParticipantsGroupsRequest {
  groupIds: string[];
}

export const apiV1ParticipantsGroupsRequestSchema: Schema<ApiV1ParticipantsGroupsRequest> = object(
  { groupIds: ['groupIds', array(string())] }
);
