/**
 * Intervengine Application API V1Lib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { boolean, nullable, object, optional, Schema, string } from '../schema';

export interface ApiV1SurveysSearchRequest {
  code?: string | null;
  name?: string;
  descriptionShort?: string | null;
  descriptionLong?: string | null;
  tagIds?: string | null;
  isActive?: boolean;
}

export const apiV1SurveysSearchRequestSchema: Schema<ApiV1SurveysSearchRequest> = object(
  {
    code: ['code', optional(nullable(string()))],
    name: ['name', optional(string())],
    descriptionShort: ['descriptionShort', optional(nullable(string()))],
    descriptionLong: ['descriptionLong', optional(nullable(string()))],
    tagIds: ['tagIds', optional(nullable(string()))],
    isActive: ['isActive', optional(boolean())],
  }
);
