/**
 * Intervengine Application API V1Lib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { array, boolean, object, optional, Schema, string } from '../schema';

export interface ApiV1ContentsSearchRequest {
  contentTypeId?: string;
  title?: string;
  tagIds?: string[];
  groupIds?: string[];
  isPublished?: boolean;
  isActive?: boolean;
}

export const apiV1ContentsSearchRequestSchema: Schema<ApiV1ContentsSearchRequest> = object(
  {
    contentTypeId: ['contentTypeId', optional(string())],
    title: ['title', optional(string())],
    tagIds: ['tagIds', optional(array(string()))],
    groupIds: ['groupIds', optional(array(string()))],
    isPublished: ['isPublished', optional(boolean())],
    isActive: ['isActive', optional(boolean())],
  }
);
