/**
 * Intervengine Application API V1Lib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  lazy,
  nullable,
  object,
  optional,
  Schema,
  string,
  unknown,
} from '../schema';
import { Preferences1, preferences1Schema } from './preferences1';

export interface ApiV1ParticipantsRequest {
  firstName: string;
  lastName: string;
  email: string;
  mobile?: string;
  gender?: string;
  dob?: string;
  tagIds?: unknown | null;
  groupIds?: unknown | null;
  externalId?: unknown | null;
  preferences?: Preferences1;
}

export const apiV1ParticipantsRequestSchema: Schema<ApiV1ParticipantsRequest> = object(
  {
    firstName: ['firstName', string()],
    lastName: ['lastName', string()],
    email: ['email', string()],
    mobile: ['mobile', optional(string())],
    gender: ['gender', optional(string())],
    dob: ['dob', optional(string())],
    tagIds: ['tagIds', optional(nullable(unknown()))],
    groupIds: ['groupIds', optional(nullable(unknown()))],
    externalId: ['externalId', optional(nullable(unknown()))],
    preferences: ['preferences', optional(lazy(() => preferences1Schema))],
  }
);
