/**
 * Intervengine Application API V1Lib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { object, optional, Schema, string } from '../schema';

export interface ApiV1PartcipantsExtrasRequest {
  extraCode?: string;
  value?: string;
}

export const apiV1PartcipantsExtrasRequestSchema: Schema<ApiV1PartcipantsExtrasRequest> = object(
  {
    extraCode: ['extraCode', optional(string())],
    value: ['value', optional(string())],
  }
);
