/**
 * Intervengine Application API V1Lib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { object, optional, Schema, string } from '../schema';

export interface ApiV1ParticipantsResponse {
  id?: string;
}

export const apiV1ParticipantsResponseSchema: Schema<ApiV1ParticipantsResponse> = object(
  { id: ['id', optional(string())] }
);
