/**
 * Intervengine Application API V1Lib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { object, optional, Schema, string } from '../schema';

export interface ApiV1ParticipantsMobileRequest {
  mobile?: string;
}

export const apiV1ParticipantsMobileRequestSchema: Schema<ApiV1ParticipantsMobileRequest> = object(
  { mobile: ['mobile', optional(string())] }
);
