/**
 * Intervengine Application API V1Lib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { object, optional, Schema, string } from '../schema';

export interface ApiV1ParticipantsPasswordRequest {
  password?: string;
}

export const apiV1ParticipantsPasswordRequestSchema: Schema<ApiV1ParticipantsPasswordRequest> = object(
  { password: ['password', optional(string())] }
);
