/**
 * Intervengine Application API V1Lib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { array, lazy, object, optional, Schema, string } from '../schema';
import { Response, responseSchema } from './response';

export interface ApiV1ParticipantsActivityResponsesRequest {
  /** The reference id to the activity card */
  activityPlanCardId?: string;
  responses?: Response[];
}

export const apiV1ParticipantsActivityResponsesRequestSchema: Schema<ApiV1ParticipantsActivityResponsesRequest> = object(
  {
    activityPlanCardId: ['activityPlanCardId', optional(string())],
    responses: ['responses', optional(array(lazy(() => responseSchema)))],
  }
);
