/**
 * Intervengine Application API V1Lib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { boolean, nullable, object, optional, Schema, string } from '../schema';

export interface ApiV1ExtrasSearchRequest {
  code?: string | null;
  name?: string | null;
  isActive?: boolean;
}

export const apiV1ExtrasSearchRequestSchema: Schema<ApiV1ExtrasSearchRequest> = object(
  {
    code: ['code', optional(nullable(string()))],
    name: ['name', optional(nullable(string()))],
    isActive: ['isActive', optional(boolean())],
  }
);
