/**
 * Intervengine Application API V1Lib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { lazy, object, optional, Schema, string } from '../schema';
import { Preferences1, preferences1Schema } from './preferences1';

export interface ApiV1ParticipantsRequest1 {
  firstName?: string;
  lastName?: string;
  gender?: string;
  dob?: string;
  preferences?: Preferences1;
}

export const apiV1ParticipantsRequest1Schema: Schema<ApiV1ParticipantsRequest1> = object(
  {
    firstName: ['firstName', optional(string())],
    lastName: ['lastName', optional(string())],
    gender: ['gender', optional(string())],
    dob: ['dob', optional(string())],
    preferences: ['preferences', optional(lazy(() => preferences1Schema))],
  }
);
