/**
 * Intervengine Application API V1Lib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { array, lazy, object, optional, Schema, string } from '../schema';
import { SurveyResponse, surveyResponseSchema } from './surveyResponse';

export interface ApiV1ParticipantsSurveyResponsesRequest {
  activityPlanCardId?: string;
  surveyId?: string;
  surveyResponses?: SurveyResponse[];
}

export const apiV1ParticipantsSurveyResponsesRequestSchema: Schema<ApiV1ParticipantsSurveyResponsesRequest> = object(
  {
    activityPlanCardId: ['activityPlanCardId', optional(string())],
    surveyId: ['surveyId', optional(string())],
    surveyResponses: [
      'surveyResponses',
      optional(array(lazy(() => surveyResponseSchema))),
    ],
  }
);
