/**
 * Intervengine Application API V1Lib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { object, optional, Schema, string } from '../schema';

export interface ApiV1AuthTokenUpgradeRequest {
  token?: string;
}

export const apiV1AuthTokenUpgradeRequestSchema: Schema<ApiV1AuthTokenUpgradeRequest> = object(
  { token: ['token', optional(string())] }
);
