/**
 * Intervengine Application API V1Lib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { array, object, optional, Schema, string } from '../schema';

export interface ApiV1ParticipantsGroupsRequest1 {
  groupIds?: string[];
}

export const apiV1ParticipantsGroupsRequest1Schema: Schema<ApiV1ParticipantsGroupsRequest1> = object(
  { groupIds: ['groupIds', optional(array(string()))] }
);
