/**
 * Intervengine Application API V1Lib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  array,
  boolean,
  number,
  object,
  optional,
  Schema,
  string,
  unknown,
} from '../schema';

export interface Asset {
  id?: string;
  uuid?: string;
  assetMimeType?: string;
  assetName?: string;
  resourceName?: string;
  resourceType?: string;
  resourceURL?: string;
  resourceThumbnailURL?: string;
  resourceSize?: number;
  assetTags?: unknown[];
  isActive?: boolean;
}

export const assetSchema: Schema<Asset> = object({
  id: ['id', optional(string())],
  uuid: ['uuid', optional(string())],
  assetMimeType: ['assetMimeType', optional(string())],
  assetName: ['assetName', optional(string())],
  resourceName: ['resourceName', optional(string())],
  resourceType: ['resourceType', optional(string())],
  resourceURL: ['resourceURL', optional(string())],
  resourceThumbnailURL: ['resourceThumbnailURL', optional(string())],
  resourceSize: ['resourceSize', optional(number())],
  assetTags: ['assetTags', optional(array(unknown()))],
  isActive: ['isActive', optional(boolean())],
});
