/**
 * Intervengine Application API V1Lib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  array,
  lazy,
  number,
  object,
  optional,
  Schema,
  string,
} from '../schema';
import { ContentElement, contentElementSchema } from './contentElement';

export interface Body {
  id?: string;
  contentId?: string;
  title?: string;
  description?: string;
  contentElements?: ContentElement[];
  uiConfigs?: string;
  displayOrder?: number;
}

export const bodySchema: Schema<Body> = object({
  id: ['id', optional(string())],
  contentId: ['contentId', optional(string())],
  title: ['title', optional(string())],
  description: ['description', optional(string())],
  contentElements: [
    'contentElements',
    optional(array(lazy(() => contentElementSchema))),
  ],
  uiConfigs: ['uiConfigs', optional(string())],
  displayOrder: ['displayOrder', optional(number())],
});
