/**
 * Intervengine Application API V1Lib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  lazy,
  number,
  object,
  optional,
  Schema,
  string,
  unknown,
} from '../schema';
import { Asset, assetSchema } from './asset';

export interface ContentElement {
  id?: string;
  assetId?: unknown;
  asset?: Asset;
  text?: string;
  displayOrder?: number;
}

export const contentElementSchema: Schema<ContentElement> = object({
  id: ['id', optional(string())],
  assetId: ['assetId', optional(unknown())],
  asset: ['asset', optional(lazy(() => assetSchema))],
  text: ['text', optional(string())],
  displayOrder: ['displayOrder', optional(number())],
});
