/**
 * Intervengine Application API V1Lib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { array, lazy, number, object, optional, Schema } from '../schema';
import { Result2, result2Schema } from './result2';

export interface ContentSearchResult {
  results?: Result2[];
  total?: number;
}

export const contentSearchResultSchema: Schema<ContentSearchResult> = object({
  results: ['results', optional(array(lazy(() => result2Schema)))],
  total: ['total', optional(number())],
});
