/**
 * Intervengine Application API V1Lib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { array, lazy, object, optional, Schema, string } from '../schema';
import { ActivityValue1, activityValue1Schema } from './activityValue1';

export interface Data1 {
  activityPlanType?: string;
  activityPlanTypeId?: string;
  activityValues?: ActivityValue1[];
}

export const data1Schema: Schema<Data1> = object({
  activityPlanType: ['activityPlanType', optional(string())],
  activityPlanTypeId: ['activityPlanTypeId', optional(string())],
  activityValues: [
    'activityValues',
    optional(array(lazy(() => activityValue1Schema))),
  ],
});
