/**
 * Intervengine Application API V1Lib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  array,
  lazy,
  nullable,
  object,
  optional,
  Schema,
  string,
  unknown,
} from '../schema';
import { ActivityValue2, activityValue2Schema } from './activityValue2';

export interface Data2 {
  id?: string;
  activityValues?: ActivityValue2[];
  scheduledAt?: string;
  reportedAt?: unknown | null;
}

export const data2Schema: Schema<Data2> = object({
  id: ['id', optional(string())],
  activityValues: [
    'activityValues',
    optional(array(lazy(() => activityValue2Schema))),
  ],
  scheduledAt: ['scheduledAt', optional(string())],
  reportedAt: ['reportedAt', optional(nullable(unknown()))],
});
