/**
 * Intervengine Application API V1Lib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { array, lazy, object, optional, Schema, string } from '../schema';
import { ActivityValue, activityValueSchema } from './activityValue';

export interface Data {
  activityPlanType: string;
  activityPlanTypeId: string;
  activityValues?: ActivityValue[];
}

export const dataSchema: Schema<Data> = object({
  activityPlanType: ['activityPlanType', string()],
  activityPlanTypeId: ['activityPlanTypeId', string()],
  activityValues: [
    'activityValues',
    optional(array(lazy(() => activityValueSchema))),
  ],
});
