/**
 * Intervengine Application API V1Lib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  array,
  boolean,
  nullable,
  object,
  optional,
  Schema,
  string,
  unknown,
} from '../schema';

export interface Group {
  id?: string;
  groupType: string;
  parentGroupId?: string | null;
  name: string;
  code: string;
  description?: string | null;
  logoUrl?: string | null;
  groupTags?: unknown[];
  isActive: boolean;
}

export const groupSchema: Schema<Group> = object({
  id: ['id', optional(string())],
  groupType: ['groupType', string()],
  parentGroupId: ['parentGroupId', optional(nullable(string()))],
  name: ['name', string()],
  code: ['code', string()],
  description: ['description', optional(nullable(string()))],
  logoUrl: ['logoUrl', optional(nullable(string()))],
  groupTags: ['groupTags', optional(array(unknown()))],
  isActive: ['isActive', boolean()],
});
