/**
 * Intervengine Application API V1Lib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { array, lazy, number, object, Schema } from '../schema';
import { Group, groupSchema } from './group';

/** Search result model containing an array of searched items and a total count */
export interface GroupSearchResult {
  results: Group[];
  total: number;
}

export const groupSearchResultSchema: Schema<GroupSearchResult> = object({
  results: ['results', array(lazy(() => groupSchema))],
  total: ['total', number()],
});
