/**
 * Intervengine Application API V1Lib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { object, optional, Schema, string } from '../schema';

export interface Id {
  id?: string;
}

export const idSchema: Schema<Id> = object({ id: ['id', optional(string())] });
