/**
 * Intervengine Application API V1Lib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { array, number, object, optional, Schema, string } from '../schema';

export interface Preferences1 {
  channelId?: string;
  timezone?: string;
  reminderHours?: number[];
}

export const preferences1Schema: Schema<Preferences1> = object({
  channelId: ['channelId', optional(string())],
  timezone: ['timezone', optional(string())],
  reminderHours: ['reminderHours', optional(array(number()))],
});
