/**
 * Intervengine Application API V1Lib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { object, optional, Schema, string } from '../schema';

export interface RESPONSEUICONFIGS1 {
  rESPONSEUITYPE?: string;
}

export const rESPONSEUICONFIGS1Schema: Schema<RESPONSEUICONFIGS1> = object({
  rESPONSEUITYPE: ['RESPONSE_UI_TYPE', optional(string())],
});
