/**
 * Intervengine Application API V1Lib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { number, object, optional, Schema, string } from '../schema';

export interface RESPONSEUICONFIGS {
  dEFAULTVALUE?: number;
  mAXVALUE?: number;
  mINVALUE?: number;
  oPTIONSELECTIONMAX?: number;
  oPTIONSELECTIONMIN?: number;
  rESPONSEUITYPE?: string;
}

export const rESPONSEUICONFIGSSchema: Schema<RESPONSEUICONFIGS> = object({
  dEFAULTVALUE: ['DEFAULT_VALUE', optional(number())],
  mAXVALUE: ['MAX_VALUE', optional(number())],
  mINVALUE: ['MIN_VALUE', optional(number())],
  oPTIONSELECTIONMAX: ['OPTION_SELECTION_MAX', optional(number())],
  oPTIONSELECTIONMIN: ['OPTION_SELECTION_MIN', optional(number())],
  rESPONSEUITYPE: ['RESPONSE_UI_TYPE', optional(string())],
});
