/**
 * Intervengine Application API V1Lib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { boolean, object, optional, Schema } from '../schema';

export interface Status {
  consented?: boolean;
  registered?: boolean;
  suspended?: boolean;
  isActive?: boolean;
}

export const statusSchema: Schema<Status> = object({
  consented: ['consented', optional(boolean())],
  registered: ['registered', optional(boolean())],
  suspended: ['suspended', optional(boolean())],
  isActive: ['isActive', optional(boolean())],
});
