/**
 * Intervengine Application API V1Lib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { array, lazy, object, optional, Schema, string } from '../schema';
import { SurveyAnswer, surveyAnswerSchema } from './surveyAnswer';

export interface SurveyResponse {
  surveyQuestionId?: string;
  /** The answer can be either surveyOptionId or answered text based on the type of question. */
  surveyAnswers?: SurveyAnswer[];
}

export const surveyResponseSchema: Schema<SurveyResponse> = object({
  surveyQuestionId: ['surveyQuestionId', optional(string())],
  surveyAnswers: [
    'surveyAnswers',
    optional(array(lazy(() => surveyAnswerSchema))),
  ],
});
