/**
 * Intervengine Application API V1Lib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { boolean, object, optional, Schema, string } from '../schema';

export interface Tag {
  id?: string;
  name: string;
  code: string;
  isActive: boolean;
}

export const tagSchema: Schema<Tag> = object({
  id: ['id', optional(string())],
  name: ['name', string()],
  code: ['code', string()],
  isActive: ['isActive', boolean()],
});
