/**
 * Intervengine Application API V1Lib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { boolean, object, optional, Schema, string } from '../schema';

export interface UiConfigs {
  sHOWLONGDESCRIPTION?: boolean;
  sHOWNAME?: boolean;
  sHOWSHORTDESCRIPTION?: boolean;
  tEMPLATE?: string;
}

export const uiConfigsSchema: Schema<UiConfigs> = object({
  sHOWLONGDESCRIPTION: ['SHOW_LONG_DESCRIPTION', optional(boolean())],
  sHOWNAME: ['SHOW_NAME', optional(boolean())],
  sHOWSHORTDESCRIPTION: ['SHOW_SHORT_DESCRIPTION', optional(boolean())],
  tEMPLATE: ['TEMPLATE', optional(string())],
});
